### ISSUE TITLE
How to use visual data?

### ISSUE THREAD

**Issue by Mikor-mkr** [MarvinStuede/cmr_lidarloop#3]
Hi @MarvinStuede, as you can understand I am very interested in your package, thanks again for making it public. Correct if I am wrong but I understand that it can work with visual data, in addition to lidar's point cloud. The thing is that I need some more info on that.

[1] First of all, what kind of visual data can be used? Can it be used with a monocular rgb camera, stereo topics, rgbd..?
[2] How should I subscribe the visual data to cmr package?

Thank you in advance.

**Comment by MarvinStuede** [comment]
Hi,

the package was developed as a method for loop detection and point cloud registration based on 3D Lidar data. It is implemented as an extension to the RTAB-Map Framework (ie. rtabmap_ros):
https://github.com/introlab/rtabmap_ros

Therefore, to use visual data it is necessary to use RTAB-Map. There are several tutorials on the RTAB-Map website on how to use visual data. The cmr_lidarloop package can then be used for RTAB-Map, to also detect loop closures with Lidar data. If you only need loop closures based on visual data, RTAB-Map by itself is sufficient.
