### ISSUE TITLE
Any interest in porting the package to ROS2?

### ISSUE THREAD

**Issue by cantolini** [MarvinStuede/cmr_lidarloop#6]
Hi,
I am using Rtabmap with a 3D Lidar on ROS2 Galactic, and I would be interested in having a way to detect good loop closures with 3D Lidar. 

Do you have any plan on adapting your solution to ROS2?

Thanks in advance!

**Comment by MarvinStuede** [comment]
Hi,
currently, we do not plan to port the package to ROS 2, as we will use our robots with ROS 1 until EOL.
